name: ChatAlert
version: 1.0
description: Plugin which enhances the chat with tagging system.
author: jacklin213

main: me.jacklin213.chatalert.ChatAlert

permissions:
  chatalert.alert:
    default: op
    description: Allows player to use the Alerting system
  chatalert.nocooldown:
    default: op
    description: Ignores cooldown