name: ChatAlert
version: 1.0
description: Disables hoe breaking lilly pads
author: jacklin213

main: me.jacklin213.chatalert.ChatAlert

permissions:
  chatalert.alert:
    default: op
    description: Allows player to use the Alerting system


